// Dummy government email IDs per state
const stateEmails = {
  "andhra pradesh":       "ap.gov.reports@gmail.com",
  "arunachal pradesh":    "arunachal.gov.reports@gmail.com",
  "assam":                "assam.gov.reports@gmail.com",
  "bihar":                "bihar.gov.reports@gmail.com",
  "chhattisgarh":         "chhattisgarh.gov.reports@gmail.com",
  "goa":                  "goa.gov.reports@gmail.com",
  "gujarat":              "gujarat.gov.reports@gmail.com",
  "haryana":              "haryana.gov.reports@gmail.com",
  "himachal pradesh":     "himachal.gov.reports@gmail.com",
  "jharkhand":            "jharkhand.gov.reports@gmail.com",
  "karnataka":            "karnataka.gov.reports@gmail.com",
  "kerala":               "kerala.gov.reports@gmail.com",
  "madhya pradesh":       "mp.gov.reports@gmail.com",
  "maharashtra":          "maharashtra.gov.reports@gmail.com",
  "manipur":              "manipur.gov.reports@gmail.com",
  "meghalaya":            "meghalaya.gov.reports@gmail.com",
  "mizoram":              "mizoram.gov.reports@gmail.com",
  "nagaland":             "nagaland.gov.reports@gmail.com",
  "odisha":               "odisha.gov.reports@gmail.com",
  "punjab":               "punjab.gov.reports@gmail.com",
  "rajasthan":            "rajasthan.gov.reports@gmail.com",
  "sikkim":               "sikkim.gov.reports@gmail.com",
  "tamil nadu":           "tamilnadu.gov.reports@gmail.com",
  "telangana":            "telangana.gov.reports@gmail.com",
  "tripura":              "tripura.gov.reports@gmail.com",
  "uttar pradesh":        "up.gov.reports@gmail.com",
  "uttarakhand":          "uttarakhand.gov.reports@gmail.com",
  "west bengal":          "westbengal.gov.reports@gmail.com",
  // Union Territories
  "delhi":                "delhi.gov.reports@gmail.com",
  "jammu and kashmir":    "jk.gov.reports@gmail.com",
  "ladakh":               "ladakh.gov.reports@gmail.com",
  "chandigarh":           "chandigarh.gov.reports@gmail.com",
  "puducherry":           "puducherry.gov.reports@gmail.com",
};

export default stateEmails;